Repository igorbrasileiro/DACA-BACKEND, pull requests merged in 2019-09, with the labels that each got.

#14 Refactor
  src/graphql/resolvers.ts
  src/graphql/resources/commission/commission.resolvers.ts
  src/graphql/resources/depute/depute.resolvers.ts
  src/graphql/resources/depute/depute.schema.ts
  src/graphql/resources/lawProject/lawProject.resolvers.ts
  src/graphql/resources/party/party.resolvers.ts
  src/graphql/resources/party/party.schema.ts
  src/graphql/resources/person/person.resolvers.ts
  src/graphql/resources/person/person.schema.ts
  src/graphql/resources/user/user.resolvers.ts
  src/graphql/typeDefs.ts
  src/interfaces/BaseModelInterface.ts
  src/interfaces/DbConnectionInterface.ts
  src/interfaces/ModelsInterface.ts
  src/models/Commission.ts
  src/models/CommissionDeputies.ts
  src/models/Depute.ts
  src/models/LawProject.ts
  src/models/Party.ts
  src/models/Person.ts
  src/models/State.ts
  src/models/index.ts
Labels: bug, refactor

#15 Vote law project
  src/graphql/resources/lawProject/lawProject.resolvers.ts
  src/graphql/resources/lawProject/lawProject.schema.ts
  src/graphql/resources/person/person.resolvers.ts
  src/models/LawProject.ts
Labels: enhancement

#16 Auth
  package.json
  src/database/migrations/21082019-state.ts
  src/database/seeders/21082019-state.ts
  src/graphql/composable/auth.resolver.ts
  src/graphql/composable/composable.resolver.ts
  src/graphql/resources/person/person.resolvers.ts
  src/graphql/resources/person/person.schema.ts
  src/index.ts
  src/interfaces/ResolverContextInterface.ts
  src/middleware/auth.ts
Labels: enhancement

#17 refactor/fix auth and person entity
  src/graphql/resolvers.ts
  src/graphql/resources/person/person.resolvers.ts
  src/graphql/resources/person/person.schema.ts
  src/graphql/resources/token/token.resolver.ts
  src/graphql/resources/token/token.schema.ts
  src/graphql/typeDefs.ts
  src/index.ts
  src/middleware/auth.ts
  src/models/Person.ts
Labels: enhancement, refactor
